### ISSUE TITLE
vlf-base elc is invalid

### ISSUE THREAD

**Issue by libichong** [m00natic/vlfi#29]
I used vlf to open a large file but met with the error "required feature vlf-base was not provided", it works after delete vlf-base.elc. I installed it from elpa.

**Comment by m00natic** [comment]
You mean GNU Elpa?  Which Emacs version?  Did you install it through
the list-packages interface?

I can't reproduce this with emacs-24.5 or current release candidate
branch and fresh install through list-packages.  There is vlf-base
provide statement where necessary, so such error is not expected with
normal install.
