### ISSUE TITLE
File rendering issues

### ISSUE THREAD

**Issue by srustamo** [m00natic/vlfi#39]
Using with GNU Emacs 25.3.1 (x86_64-apple-darwin13.4.0, Carbon Version 157 AppKit 1265.21) of 2017-10-23.

Only some portion of the first chunk is legible of the 1.2Gb apache log.  The rest is illegible as shown as on the screenshot attached.

What might be the problem?
<img width="2000" alt="screen shot 2017-11-20 at 6 42 46 pm" src="https://user-images.githubusercontent.com/749813/33021299-2ef6f528-ce23-11e7-95cc-542cef123695.png">

**Comment by srustamo** [comment]
Just notice, if I scroll with mouse to the end of the first chunk, it renders the whole chunk legibly. It then opens the next chunk and it also is legible, if scrolled by mouse. It seems that jumping with `C-c-v n` starts producing illegible buffer, as also with `C-c-v ]`.

**Comment by srustamo** [comment]
Tried to scroll with mouse as far down the file as possible. The rendering is good only upto chunk 4, about first half.

**Comment by m00natic** [comment]
What's the encoding of this file?  It seems it's properly detected in
the beginning but when jumping it falls to no-conversion (the '=' in the
modeline).

**Comment by srustamo** [comment]
When the file is first loaded, Emacs reports `multi-byte: undecided-unix`. The file is generated on a Win Server 2012 box.

**Comment by srustamo** [comment]
I tried opening the file with console app on mac, the tail end of the file shows up empty. There might be a problem with the file itself.

**Comment by m00natic** [comment]
Is it possible that parts of it are human readable and other regions are
binary?  Is this file too big to load it all in Emacs (for science!) and
see how much is legible... By definition, this is the best VLF could
aspire to as far as encoding detection goes.

**Comment by srustamo** [comment]
I tried opening it in Emacs, but did not have enough patience after watching it struggle for over 5 min. and nothing happening.
